
services:
  api-gateway:
    build: 
      context: .
      dockerfile: ./apps/api-gateway/Dockerfile
    container_name: turbo-api
    ports:
      - "4000:4000"

    env_file:
      - ./apps/api-gateway/.env
    volumes:
      - .:/app
      - /app//apps/api-gateway/node_modules
      - /app/node_modules
    environment:
      - PORT=4000
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
    command: pnpm --filter api-gateway start
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: turbo-redis
    ports:
      - "6379:6379"